services:
  postgres_db:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MAX_CONNECTIONS: 200
      POSTGRES_SHARED_BUFFERS: 256MB
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
      -c log_connections=on
      -c log_disconnections=on
      -c log_line_prefix='%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
      -c log_destination='stderr'
      -c logging_collector=off
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_init:
    build:
      context: .
      dockerfile: services/db_init/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
      - APP_USER=${APP_USER:-app_user}
      - APP_PASSWORD=${APP_PASSWORD:-app_password}
      - LOG_LEVEL=info
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: "no"
  
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_LOG_LEVEL=debug
      - RABBITMQ_FIREHOSE_TRACER=true
      - RABBITMQ_TRACE=1
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
      - ./services/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  socket_io:
    build:
      context: .
      dockerfile: services/socket_io/Dockerfile
    ports:
      - "${SOCKET_IO_PORT}:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    ports:
      - "${USERS_PORT}:8001"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - RABBITMQ_URL=${RABBITMQ_URL}
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    volumes:
      - ./.env:/app/.env
    depends_on:
      postgres_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      db_init:
        condition: service_completed_successfully
    tty: true
    stdin_open: true
  
  notifications:
    build:
      context: .
      dockerfile: services/notifications/Dockerfile
    ports:
      - "${NOTIFICATIONS_PORT}:8002"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  presence:
    build:
      context: .
      dockerfile: services/presence/Dockerfile
    ports:
      - "${PRESENCE_PORT}:8003"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - RABBITMQ_URL=${RABBITMQ_URL}
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      postgres_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      db_init:
        condition: service_completed_successfully
  
  chat:
    build:
      context: .
      dockerfile: services/chat/Dockerfile
    ports:
      - "${CHAT_PORT}:8004"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    env_file:
      - .env
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:8001}
      - VITE_SOCKET_URL=${SOCKET_URL:-http://localhost:8000}
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_logs: